### ISSUE TITLE
Push Redis logs to logstash 

### ISSUE THREAD

**Issue by KenPet11** [brusMX/promitor-tests#31]
Configure managed resource to send logs to EventHub then pass in config file into logstash to pull from EventHub.

Check: Can see resources in Kibana dashboard  

Managed Resource: Redis

**Comment by cnadolny** [comment]
Issue: Redis does export logs in Diagnostic Settings, it seems like they're all groups together as "metrics".

https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-monitor#available-metrics-and-reporting-intervals
