### ISSUE TITLE
Scrape metrics from Redis PostgreSQL

### ISSUE THREAD

**Issue by KenPet11** [brusMX/promitor-tests#4]
Relevant to answer the question: what metrics can we scrape?

**Comment by brusMX** [comment]
1. For PostgreSQL - https://docs.microsoft.com/en-us/azure/postgresql/concepts-monitoring#list-of-metrics
1. For Redis - https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-monitor#available-metrics-and-reporting-intervals

Now, that doesn't mean that they will all be exposed or that the naming is consistent between the dashboard and the metrics API, we need to verify that. @cnadolny is testing some for PotsgreSQL

**Comment by cnadolny** [comment]
Verified that Promitor is able to grab the metrics listed here:
https://docs.microsoft.com/en-us/azure/postgresql/concepts-monitoring#list-of-metrics

**Comment by cnadolny** [comment]
Verified that Redis is also able to grab the metrics listed here:
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftcacheredis
